### PR TITLE
Define multiple sources, plain function import, properly escape URLs

### PR DESCRIPTION
**Pull request by tommikaikkonen**
Fixes:
- https://github.com/pancentric/django-imgix/issues/5 (ability to define multiple sources)
- URLs not being escaped in templates on older Django versions

Sorry for submitting a larger PR without asking if these changes are in line with you guys - however all the tests pass and the only breaking change is arguments overriding aliases. Let me know what you think.

- Added a normal function import for `imgix.get_imgix_url` that has the same signature as `get_imgix` template tag
- Added `IMGIX_SOURCES` setting to specify multiple sources, which is a dictionary that maps arbitrary source names to dictionaries that define the settings for each source. Check the updated README.md and code for details.
- Added optional `source` keyword argument to `get_imgix` template tag and `get_imgix_url` function.
- Previously setting an alias would ignore other arguments. To be more in line with `easy-thumbnails` and more useful in my opinion, additional arguments override the alias. Let me know if there was specific reasoning for the previous logic.
- Tests for Django 1.9 and 1.10

Internal:
- Refactored `get_settings` to `get_sources`, which returns a dict where keys correspond to `imgix.UrlBuilder` constructor kwargs.
- Separated `wh` argument parsing to it's own function
- Wrote separate `get_alias` function to replace `get_kwargs`
- Added a couple utility functions to `utils.py`
- Added Django 1.9 and Django 1.10 to the tox suite. Added the `TEMPLATES` setting variable needed for those versions.
- Updated docstrings and README.md for these changes
- Added myself to AUTHORS
- Added these changes to CHANGELOG

### CODE REVIEW

**Comment by tommikaikkonen** [comment]
I'm working on an update to this that uses a separate `IMGIX_SOURCES` setting - it's a lot cleaner. Will update this PR when I'm done.

**Comment by tommikaikkonen** [comment]
Ok, done with that update. Updated the PR description. Let me know what you think!

**Comment by dtran320** [comment]
+1 for this

**Comment by luqven** [comment]
Closing this since there hasn't been any activity in a long time. Please feel free to tag me if this is still relevant.

**Pull request closed without merging**
